image: atlassian/default-image:2
pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - apt-get update
          - apt-get install curl unzip
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - REPO=
          - CLUSTER_N=
          - AWS_REGION=
          - IMAGE=$REPO/$CLUSTER_N
          - TAG=${BITBUCKET_BUILD_NUMBER}
          - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
          - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
          - aws configure set default.region $AWS_REGION
          - aws configure set default.output json
          - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO
          - docker build -t $IMAGE:$TAG .
          - docker push $IMAGE:$TAG
          - envsubst < deployment.yaml > deployment1.yaml
          - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - mv ./kubectl /usr/bin/kubectl
          - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_N
          - kubectl apply -f deployment1.yaml
          - kubectl apply -f service.yaml
          - sleep 15
          - kubectl get services

